---
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
serviceWeb:
  loadBalancerIP: 192.168.1.250
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.1.250
  type: LoadBalancer

dnsmasq:
  customDnsEntries:
    - address=/dashboard.picocloud.io/192.168.1.250
    - address=/argo.picocloid.io/192.168.1.250
    - address=/argocd.picocloud.io/192.168.1.250
    - address=/pihole.picocloud.io/192.168.1.250

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

adminPassword: admin
