apiVersion: v1
data:
  delegation-default.conf: "server {\n\tlisten       80 default;\n\tlocation / {\n\t\treturn
    200;\n\t}\n\tlocation /.well-known/matrix/server {\n\t\tdefault_type application/json;\n\t\treturn
    200 '{\"m.server\": \"matrix.spark.im:443\"}';\n\t}\n\tlocation /.well-known/matrix/client
    {\n\t\tdefault_type application/json;\n\t\treturn 200 '{\"m.homeserver\": { \"base_url\":
    \"https://matrix.spark.im\" }}';\n        }\n}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: delegation-conf
