worker_app: synapse.app.generic_worker
worker_name: presence

# The replication listener on the synapse to talk to.
worker_replication_host: synapse-master
worker_replication_http_port: 9093

worker_log_config: /data/workers/presence_log_config.yaml

worker_listeners:
  - type: http
    bind_addresses: ['0.0.0.0']
    port: 9090
    tls: false
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false

  - type: http
    bind_addresses: ['0.0.0.0']
    port: 9100
    resources:
      - names: [replication]

  - type: metrics
    bind_addresses: ['0.0.0.0']
    port: 9091
