worker_app: synapse.app.pusher
worker_name: pusher

# The replication listener on the synapse to talk to.
worker_replication_host: synapse-master
worker_replication_http_port: 9093

worker_log_config: /data/workers/pusher_log_config.yaml

worker_listeners:
  - type: metrics
    bind_addresses: ['0.0.0.0']
    port: 9091
