---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: matrix-synapse
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 32132
    name: postgres
  type: NodePort
  selector:
    app: postgres