---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: matrix-synapse
  labels:
    app: postgres
data:
  POSTGRES_DB: synapse-db
  POSTGRES_USER: synapse
  POSTGRES_PASSWORD: postgres123
  POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF-8"