---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: matrix-synapse
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        args:
        - -c
        - config_file=/etc/postgresql/conf/my-postgres.conf
        envFrom:
        - configMapRef:
            name: postgres-configuration
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: pgconfig-volume
          mountPath: /etc/postgresql/conf
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: pgconfig-volume
        configMap:
          name: postgres-config